#!/usr/extra/bin/ksh
# GNU Compiler Collection
PN=${0##*/}
RF_OK=true
INCDIR=include
if [[ ! -d ${INCDIR} ]] ; then
  INCDIR=${REPOROOT}/include
  if [[ ! -d ${INCDIR} ]] ; then
    ED_OK=false
    print -u2 "${PN}: no repository root found"
  fi
fi
if [[ -n "${INCDIR}" ]] && [[ -d "${INCDIR}" ]] ; then
  INCDIRS="-I${INCDIR}"
fi
PROG="print -u2 -- ${PN}: no-program"
if ${RF_OK} ; then
OPTS=
case ${PN} in
gcpp*)
  PROG=gcpp13
  OPTS="${INCDIRS}"
  ;;
gcc*)
  PROG=gcc13
  OPTS="${INCDIRS}"
  ;;
gpp*)
  PROG=gpp13
  OPTS="${INCDIRS}"
  ;;
gld*)
  PROG=gld13
  ;;
granlib*)
  PROG=granlib13
  ;;
gar*)
  PROG=gar13
  ;;
gnm*)
  PROG=gnm13
  ;;
gcov*)
  PROG=gcov13
  ;;
esac
${PROG} ${OPTS} "${@}"
fi

