#!/usr/local/bin/ksh
# MKLINKS (testtermbold)

CMDS+=" termbold "

LOCPROG=testtermbold.x
TDIRS=" /usr/extra /usr/local "

function linkdir {
  typeset TDIR=${1}
  for C in ${CMDS} ; do
    ln -f ${LOCPROG} ${TDIR}/bin/${C}
  done
} # end function

if [[ -x "${LOCPROG}" ]] ; then
  for D in ${TDIRS} ; do
    if [[ -d "${D}" ]] ; then
      linkdir $D
    else
      print -u 2 -- "target directory not present"
      break ;
    fi
  done
else
  print -u 2 -- "program not made"
fi


